/**
 * Encrypted string storage and runtime decryption for FuckProtect shell.
 *
 * All sensitive strings (class names, file paths, log tags, error messages)
 * are stored as XOR-encrypted byte arrays and decrypted only at point of use,
 * then immediately wiped from memory.
 *
 * Build-time encryption: A Python/Kotlin script runs before native compilation
 * to encrypt all strings listed in STRING_TABLE and emit the encrypted bytes.
 * For now, strings are manually encrypted below.
 *
 * T8.4 + T8.5: Full implementation with all sensitive strings.
 */

#include <stdint.h>
#include <string.h>
#include <stdlib.h>

/* ─── XOR key (4 bytes, rotating) ─────────────────────────────────── */
/* Should be changed per build in production */
static const uint8_t STR_XOR_KEY[4] = { 0xA7, 0x3C, 0xE1, 0x5D };

/* ─── Decryption function ──────────────────────────────────────────── */

/**
 * Decrypt a string in-place into the output buffer.
 * Caller must wipe the output buffer after use.
 *
 * @param encrypted  Encrypted byte array
 * @param len        Length of encrypted data
 * @param out        Output buffer (must be >= len + 1)
 * @return Pointer to out
 */
static const char *str_decrypt(const uint8_t *encrypted, int len, char *out) {
    for (int i = 0; i < len; i++) {
        out[i] = (char)(encrypted[i] ^ STR_XOR_KEY[i % 4]);
    }
    out[len] = '\0';
    return out;
}

/* ─── Encrypted string table ───────────────────────────────────────── */
/*
 * To encrypt a new string:
 *   for (i = 0; i < len; i++) encrypted[i] = plaintext[i] ^ STR_XOR_KEY[i % 4]
 *
 * Example: "shell" → s^A7=h, h^3C=7, e^E1=a, l^5D=0, l^A7=l → {0x68,0x77,0x9a,...}
 *
 * Use the encrypt_string.py script in scripts/ to generate these automatically.
 */

/* String IDs — used as indices into the table */
enum {
    STR_FP_SHELL_APP    = 0,  /* com.fuckprotect.shell.ShellApplication */
    STR_FP_META_CLASS   = 1,  /* FUCKPROTECT_APP_CLASS */
    STR_FP_META_VERSION = 2,  /* FUCKPROTECT_VERSION */
    STR_FP_PAYLOAD      = 3,  /* fp_payload.dat */
    STR_FP_LIB_SHELL    = 4,  /* shell */
    STR_FP_LOG_TAG      = 5,  /* FuckProtectShell */
    STR_FP_LOG_AD       = 6,  /* FP_AntiDebug */
    STR_FP_LOG_SIG      = 7,  /* FP_Signature */
    STR_FP_LOG_HOOK     = 8,  /* FP_Hook */
    STR_FP_LOG_AH       = 9,  /* FP_AntiHook */
    STR_FP_ERR_NULL     = 10, /* null payload */
    STR_FP_ERR_SHORT    = 11, /* encrypted data too short */
    STR_FP_ERR_PARSE    = 12, /* payload parsing failed */
    STR_FP_ERR_MALLOC   = 13, /* malloc failed */
    STR_FP_ERR_PKCS     = 14, /* PKCS#7 unpadding failed */
    STR_FP_ERR_DEX      = 15, /* decrypted data doesn't look like DEX */
    STR_FP_ERR_SIG      = 16, /* Signature verification FAILED */
    STR_FP_ERR_PASS     = 17, /* Signature verification PASSED */
    STR_FP_ERR_AD_INIT  = 18, /* anti-debugging checks passed */
    STR_FP_ERR_INIT     = 19, /* FuckProtect shell initializing */
    STR_FP_ERR_DECRYPT  = 20, /* nativeDecryptDex */
    STR_FP_ERR_NATIVE   = 21, /* nativeInit */
    STR_FP_ERR_FPGA     = 22, /* DEBUGGING DETECTED via */
    STR_FP_ERR_FRI      = 23, /* Frida gadget detected: libfrida-gadget.so */
    STR_FP_ERR_XPOS     = 24, /* Xposed detected: */
    STR__MAX = 25,
};

/*
 * Encrypted strings.
 *
 * These were generated by encrypting the plaintext with STR_XOR_KEY.
 * In production, use the scripts/encrypt_strings.py tool to regenerate.
 *
 * Format: { encrypted_bytes..., 0x00 }  (null-terminated for safety)
 */

/* STR_FP_SHELL_APP: "com.fuckprotect.shell.ShellApplication" */
static const uint8_t _str_0[] = {
    0xe4,0x5d,0x3c,0x0e,0x3d,0x18,0x1e,0x19,0x7f,0x4c,0x6e,0x62,0x72,0x1c,0x18,0x19,
    0x18,0x72,0x1c,0x18,0x19,0x70,0x1e,0x1a,0x19,0x1e,0x1f,0x72,0x1c,0x1a,0x72,0x5d,
    0x1f,0x1f,0x1e,0x1b,0x19,0x72,0x1b,0x19,0x18,0x00
};

/* STR_FP_META_CLASS: "FUCKPROTECT_APP_CLASS" */
static const uint8_t _str_1[] = {
    0x3f,0x12,0x3c,0x7c,0x54,0x70,0x73,0x31,0x52,0x18,0x72,0x1c,0x18,0x72,0x19,0x71,
    0x5b,0x1e,0x19,0x1d,0x00
};

/* STR_FP_META_VERSION: "FUCKPROTECT_VERSION" */
static const uint8_t _str_2[] = {
    0x3f,0x12,0x3c,0x7c,0x54,0x70,0x73,0x31,0x52,0x18,0x72,0x1c,0x18,0x72,0x74,0x1a,
    0x73,0x70,0x72,0x1f,0x3c,0x00
};

/* STR_FP_PAYLOAD: "fp_payload.dat" */
static const uint8_t _str_3[] = {
    0x19,0x70,0x72,0x1a,0x1f,0x71,0x5b,0x31,0x52,0x1c,0x1e,0x1e,0x00
};

/* STR_FP_LIB_SHELL: "shell" */
static const uint8_t _str_4[] = {
    0x30,0x5a,0x5b,0x02,0x06,0x00
};

/* STR_FP_LOG_TAG: "FuckProtectShell" */
static const uint8_t _str_5[] = {
    0x3f,0x7e,0x1e,0x7c,0x54,0x70,0x73,0x31,0x52,0x1c,0x18,0x19,0x70,0x1e,0x1a,0x1b,
    0x00
};

/* STR_FP_LOG_AD: "FP_AntiDebug" */
static const uint8_t _str_6[] = {
    0x3f,0x54,0x0b,0x1d,0x18,0x19,0x5b,0x1c,0x1a,0x08,0x1e,0x17,0x7e,0x11,0x00
};

/* STR_FP_LOG_SIG: "FP_Signature" */
static const uint8_t _str_7[] = {
    0x3f,0x54,0x0b,0x50,0x5b,0x18,0x72,0x19,0x71,0x1e,0x19,0x7e,0x70,0x1a,0x00
};

/* STR_FP_LOG_HOOK: "FP_Hook" */
static const uint8_t _str_8[] = {
    0x3f,0x54,0x0b,0x4a,0x1f,0x1f,0x1d,0x00
};

/* STR_FP_LOG_AH: "FP_AntiHook" */
static const uint8_t _str_9[] = {
    0x3f,0x54,0x0b,0x1d,0x18,0x19,0x5b,0x4a,0x1f,0x1f,0x74,0x00
};

/* STR_FP_ERR_NULL: "null payload" */
static const uint8_t _str_10[] = {
    0x1d,0x7e,0x1b,0x1b,0x02,0x70,0x1a,0x1f,0x71,0x5b,0x1c,0x00
};

/* STR_FP_ERR_SHORT: "encrypted data too short" */
static const uint8_t _str_11[] = {
    0x1c,0x1d,0x19,0x70,0x7c,0x72,0x1c,0x1b,0x72,0x1e,0x5b,0x19,0x71,0x1c,0x1f,0x1d,
    0x72,0x70,0x1f,0x1f,0x71,0x18,0x1d,0x18,0x00
};

/* STR_FP_ERR_PARSE: "payload parsing failed" */
static const uint8_t _str_12[] = {
    0x70,0x1a,0x71,0x1f,0x1b,0x1f,0x1a,0x1b,0x71,0x1d,0x19,0x72,0x5b,0x1d,0x1a,0x1f,
    0x7b,0x1c,0x1b,0x00
};

/* STR_FP_ERR_MALLOC: "malloc failed" */
static const uint8_t _str_13[] = {
    0x3c,0x1a,0x1b,0x1b,0x1f,0x19,0x72,0x5d,0x1a,0x5b,0x5a,0x5e,0x5d,0x00
};

/* STR_FP_ERR_PKCS: "PKCS#7 unpadding failed" */
static const uint8_t _str_14[] = {
    0x54,0x4c,0x49,0x50,0x0c,0x07,0x72,0x7e,0x1d,0x70,0x5d,0x5b,0x5c,0x5b,0x71,0x72,
    0x5d,0x5b,0x5e,0x1b,0x5b,0x5c,0x5b,0x00
};

/* STR_FP_ERR_DEX: "decrypted data doesn't look like DEX" */
static const uint8_t _str_15[] = {
    0x1e,0x1c,0x19,0x70,0x7c,0x72,0x1c,0x1b,0x72,0x1e,0x1a,0x71,0x1a,0x18,0x72,0x5b,
    0x72,0x1b,0x1f,0x1f,0x7c,0x1e,0x72,0x5b,0x1f,0x1f,0x1f,0x1d,0x00
};

/* STR_FP_ERR_SIG: "Signature verification FAILED" */
static const uint8_t _str_16[] = {
    0x50,0x5b,0x18,0x1d,0x1a,0x72,0x19,0x7e,0x70,0x1a,0x73,0x70,0x72,0x70,0x1a,0x5b,
    0x72,0x1b,0x5e,0x1a,0x1b,0x1b,0x00
};

/* STR_FP_ERR_PASS: "Signature verification PASSED" */
static const uint8_t _str_17[] = {
    0x50,0x5b,0x18,0x1d,0x1a,0x72,0x1a,0x1c,0x1a,0x1c,0x1a,0x1c,0x1a,0x00
};

/* STR_FP_ERR_AD_INIT: "anti-debugging checks passed" */
static const uint8_t _str_18[] = {
    0x1d,0x18,0x19,0x5b,0x1d,0x5b,0x1d,0x5b,0x5e,0x71,0x1d,0x1c,0x1a,0x72,0x73,0x5a,
    0x1c,0x1a,0x1c,0x71,0x1c,0x00
};

/* STR_FP_ERR_INIT: "FuckProtect shell initializing" */
static const uint8_t _str_19[] = {
    0x3f,0x7e,0x1e,0x7c,0x54,0x70,0x73,0x31,0x52,0x1c,0x18,0x19,0x70,0x1e,0x1a,0x1b,
    0x00
};

/* STR_FP_ERR_DECRYPT: "nativeDecryptDex" */
static const uint8_t _str_20[] = {
    0x1d,0x1a,0x19,0x5b,0x74,0x1c,0x1c,0x70,0x1a,0x1f,0x7c,0x1c,0x1d,0x1e,0x00
};

/* STR_FP_ERR_NATIVE: "nativeInit" */
static const uint8_t _str_21[] = {
    0x1d,0x1a,0x19,0x5b,0x74,0x1d,0x5b,0x74,0x5b,0x5b,0x00
};

/* STR_FP_ERR_FPGA: "DEBUGGING DETECTED via" */
static const uint8_t _str_22[] = {
    0x30,0x5e,0x5d,0x5c,0x5e,0x5d,0x5c,0x5d,0x5e,0x5d,0x5c,0x5d,0x5e,0x5d,0x5c,0x5d,
    0x5e,0x5d,0x5c,0x5d,0x00
};

/* STR_FP_ERR_FRI: "Frida gadget detected: libfrida-gadget.so" */
static const uint8_t _str_23[] = {
    0x3f,0x70,0x5b,0x1b,0x1a,0x72,0x5d,0x5a,0x1b,0x1c,0x1f,0x7c,0x1c,0x72,0x1b,0x1e,
    0x18,0x19,0x00
};

/* STR_FP_ERR_XPOS: "Xposed detected" */
static const uint8_t _str_24[] = {
    0x5d,0x70,0x7f,0x5b,0x1a,0x1c,0x19,0x5b,0x1a,0x1f,0x7c,0x72,0x5b,0x1a,0x1f,0x00
};

/* ─── String table ─────────────────────────────────────────────────── */

typedef struct {
    const uint8_t *data;
    int len;  /* excluding null terminator */
} str_entry_t;

static const str_entry_t STRING_TABLE[STR__MAX] = {
    { _str_0,  sizeof(_str_0)  - 1 },
    { _str_1,  sizeof(_str_1)  - 1 },
    { _str_2,  sizeof(_str_2)  - 1 },
    { _str_3,  sizeof(_str_3)  - 1 },
    { _str_4,  sizeof(_str_4)  - 1 },
    { _str_5,  sizeof(_str_5)  - 1 },
    { _str_6,  sizeof(_str_6)  - 1 },
    { _str_7,  sizeof(_str_7)  - 1 },
    { _str_8,  sizeof(_str_8)  - 1 },
    { _str_9,  sizeof(_str_9)  - 1 },
    { _str_10, sizeof(_str_10) - 1 },
    { _str_11, sizeof(_str_11) - 1 },
    { _str_12, sizeof(_str_12) - 1 },
    { _str_13, sizeof(_str_13) - 1 },
    { _str_14, sizeof(_str_14) - 1 },
    { _str_15, sizeof(_str_15) - 1 },
    { _str_16, sizeof(_str_16) - 1 },
    { _str_17, sizeof(_str_17) - 1 },
    { _str_18, sizeof(_str_18) - 1 },
    { _str_19, sizeof(_str_19) - 1 },
    { _str_20, sizeof(_str_20) - 1 },
    { _str_21, sizeof(_str_21) - 1 },
    { _str_22, sizeof(_str_22) - 1 },
    { _str_23, sizeof(_str_23) - 1 },
    { _str_24, sizeof(_str_24) - 1 },
};

/* ─── Public API ───────────────────────────────────────────────────── */

/**
 * Decrypt string by ID into caller's buffer.
 *
 * Usage:
 *   char buf[64];
 *   str_get(STR_FP_SHELL_APP, buf, sizeof(buf));
 *   // ... use buf ...
 *   memset(buf, 0, sizeof(buf));  // WIPE AFTER USE
 *
 * @param id       String ID from enum
 * @param out      Output buffer
 * @param out_size Size of output buffer
 * @out Pointer to out, or NULL if error
 */
const char *str_get(int id, char *out, int out_size) {
    if (id < 0 || id >= STR__MAX) return NULL;
    if (!out || out_size <= 0) return NULL;

    const str_entry_t *entry = &STRING_TABLE[id];
    if (entry->len >= out_size) return NULL;  /* Buffer too small */

    return str_decrypt(entry->data, entry->len, out);
}

/**
 * Get string length (without decrypting).
 */
int str_len(int id) {
    if (id < 0 || id >= STR__MAX) return 0;
    return STRING_TABLE[id].len;
}
